version: "2"
services:
  ui:
    image: ${SP_DOCKER_REGISTRY}streampipes/ui:${SP_UI_VERSION}
    ports:
      - "80:80"
    depends_on:
      - db
      - backend
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
