version: "2"
services:
  backend:
    image: ${SP_DOCKER_REGISTRY}streampipes/backend:${SP_BACKEND_VERSION}
    depends_on:
      - db
    ports:
      - "8030:8030"
    volumes:
      - ./config:/root/.streampipes
      - ./config/RDF4J:/root/.RDF4J
